- name: Deploy Podman development environment
  hosts: podman-lab
  become: true
  vars_files:
    - inventories/development/group_vars/secret.yml
  roles:
    - podman_install
    - deploy_containers
    - add_ldap_entries
    - configure_guacamole
