---
vm:
  hosts:
    guacamole-lab:
      ansible_host: 192.158.200.10
      ansible_python_interpreter: /usr/bin/python3.6
  vars:
    ansible_user: vagrant
    ansible_ssh_private_key_file: ./.vagrant/machines/guacamole-lab/libvirt/private_key
